# Generated by Django 4.1 on 2022-08-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_owner",
            name="age",
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_car",
                to="relations.car_owner",
            ),
        ),
    ]
